<template>
  <div class="card_wrapper">
    <!-- Filter -->
    <!-- <TopFilter /> -->
    <!-- Jobs -->
    <!-- <JobsCard /> -->
    <!-- Job Details -->
    <div class="job_details_wrapper">
      <!-- Share Top part -->
      <ShareJobBar />

      <!-- Job Details Data -->
      <div class="job_details_data_wrapper w-full d-flex flex-column">
        <div class="job_details_data_title">
          <h2 class="display-1">
            Canva is Hiring a Principal Product Marketing Manager, Ecosystem
          </h2>
          <v-divider
            class="my-5"
            style="
              max-width: 10%;
              min-height: 4px;
              background-color: rgb(26, 162, 210);
            "
          />
        </div>
        <div class="d-flex align-start flex-row w-full">
          <div class="JD_wrapper">
            <h4>What you’d be doing in this role:</h4>
            <span>
              Ensure that the CNC machines and machine room are clean, in proper
              state of operating at all times; Operate all CNC machines;
              Fabricate parts from Aluminum, steel and other exotic alloys;
              Consign the actual fabrication times and stock weights in the
              appropriate log; Verify parts tolerances and mechanical assembly
              clearances; Verify general part surface quality; Log machine hours
              and machine problems on the machine log; Establish and follow up
              on interval maintenance programs; Verify cutters stock, cutters
              condition.
            </span>
            <h4 class="mt-10">Mechanical Production duties:</h4>
            <ul>
              <li>
                Ensure that the CNC machines and machine room are clean, in
                proper state of operating at all times
              </li>
              <li>Operate all CNC machines;</li>
              <li>
                Fabricate parts from Aluminum, steel and other exotic alloys;
              </li>
              <li>
                Consign the actual fabrication times and stock weights in the
                appropriate log;
              </li>
              <li>
                Verify parts tolerances and mechanical assembly clearances;
              </li>
              <li>Verify cutters stock, cutters condition.</li>
            </ul>
            <h4 class="mt-10">Mechanical Production duties:</h4>
            <ul>
              <li>
                Read and analyze the CAD generated by the design engineer;
              </li>
              <li>Assist the programmer in generating tool path;</li>
              <li>
                Assist in noting machining times and stock weights in the
                appropriate system to generate cost sheets;
              </li>
              <li>
                Verify versus actual times and stock weight and generate a
                warning in case of discrepancies.
              </li>
            </ul>
          </div>

          <ApplyNowBox v-if="!applicationForm" @OpenApplicationForm="applicationForm=true" />
          <ApplicationForm v-if="applicationForm" @CloseApplicationForm="applicationForm=false" />
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import TopFilter from '@/components/TopFilter.vue'
import JobsCard from '@/components/JobsCard.vue'
import ApplyNowBox from '@/components/ApplyNowBox.vue'
import ApplicationForm from '@/components/ApplicationForm.vue'
import ShareJobBar from '@/components/ShareJobBar.vue'

export default {
  components: { TopFilter, JobsCard, ApplyNowBox, ApplicationForm, ShareJobBar },
  props: {},
  data() {
    return {
      applicationForm: false,
    }
  },
  methods: {
    handleSubmitForm() {
      console.log('form submitted');
      this.$router.push('./thank-you')
    },
  }
}
</script>

<style lang="scss"></style>
