<template>
  <div class="card_wrapper">
    <!-- Filter -->
    <!-- <TopFilter /> -->
    <!-- Jobs -->
    <!-- <JobsCard /> -->
    <!-- Job Details -->
    <div class="job_details_wrapper">
      <!-- Share Top part -->
      <div class="share_job d-flex aling-center justify-space-between w-full">
        <div class="d-flex align-center">
          <div class="share_chip">
            <v-icon small color="gray">mdi-share-variant-outline</v-icon>
            <span>Copy Link</span>
          </div>
          <div class="share_chip">
            <v-icon small color="gray">mdi-linkedin</v-icon>
            <span>Share</span>
          </div>
          <div class="share_chip">
            <v-icon small color="gray">mdi-facebook</v-icon>
            <span>Share</span>
          </div>
          <div class="share_chip">
            <v-icon small color="gray">mdi-twitter</v-icon>
            <span>Share</span>
          </div>
        </div>
        <span class="blue-grey lighten-5 pa-2 px-4 rounded">Marketing</span>
      </div>
      <v-divider class="mt-5 mb-10" />

      <!-- Job Details Data -->
      <div class="job_details_data_wrapper w-full d-flex flex-column">
        <!-- job title -->
        <div class="job_details_data_title">
          <h2 class="display-1">
            Canva is Hiring a Principal Product Marketing Manager, Ecosystem
          </h2>
          <v-divider
            class="my-5"
            style="
              max-width: 10%;
              min-height: 4px;
              background-color: rgb(26, 162, 210);
            "
          />
        </div>

        <div class="d-flex align-start flex-row w-full">
          <!-- JD -->
          <div class="JD_wrapper">
            <h4>What you’d be doing in this role:</h4>
            <span>
              Ensure that the CNC machines and machine room are clean, in proper
              state of operating at all times; Operate all CNC machines;
              Fabricate parts from Aluminum, steel and other exotic alloys;
              Consign the actual fabrication times and stock weights in the
              appropriate log; Verify parts tolerances and mechanical assembly
              clearances; Verify general part surface quality; Log machine hours
              and machine problems on the machine log; Establish and follow up
              on interval maintenance programs; Verify cutters stock, cutters
              condition.
            </span>

            <h4 class="mt-10">Mechanical Production duties:</h4>
            <ul>
              <li>
                Ensure that the CNC machines and machine room are clean, in
                proper state of operating at all times
              </li>
              <li>Operate all CNC machines;</li>
              <li>
                Fabricate parts from Aluminum, steel and other exotic alloys;
              </li>
              <li>
                Consign the actual fabrication times and stock weights in the
                appropriate log;
              </li>
              <li>
                Verify parts tolerances and mechanical assembly clearances;
              </li>
              <li>Verify cutters stock, cutters condition.</li>
            </ul>

            <h4 class="mt-10">Mechanical Production duties:</h4>
            <ul>
              <li>
                Read and analyze the CAD generated by the design engineer;
              </li>
              <li>Assist the programmer in generating tool path;</li>
              <li>
                Assist in noting machining times and stock weights in the
                appropriate system to generate cost sheets;
              </li>
              <li>
                Verify versus actual times and stock weight and generate a
                warning in case of discrepancies.
              </li>
            </ul>

            <v-btn
              large
              small
              x-large
              color="blue"
              elevation="0"
              class="ma-0 pa-0 px-15 py-2 mb-7 mt-10"
              ><span class="text-white">Apply Now</span></v-btn
            >
          </div>

          <!-- Apply now Box -->
          <!-- <div class="apply_now_box flex-column">
            <v-btn
              large
              small
              x-large
              color="blue"
              elevation="0"
              class="ma-0 pa-0 px-15 py-2 mb-7"
              ><span class="text-white">Apply Now</span></v-btn
            >
            <div class="d-flex align-center flex-column text-center">
              <v-img
                src="https://authenticjobs.com/wp-content/uploads/job-manager-uploads/company_logo/2023/10/Tanuki_white_square.png"
                max-width="65px"
                max-hight="65px"
              />
              <div class="d-flex flex-column">
                <h5>Product Design</h5>
                <span class="">San Francisco, California</span>
              </div>
            </div>
          </div> -->

          <div class="apply_now_form d-flex flex-column">
            <div class="d-flex align-start justify-space-between">
              <div class="">
                <h3>Submit your Application</h3>
                <span>Let fill the information below</span>
              </div>
              <v-icon small>mdi-close</v-icon>
            </div>
            <div class="form_wrapper">
              <div class="d-flex">
                <v-text-field label="First Name" outlined dense></v-text-field>
                <v-text-field
                  class="ml-1"
                  label="Last Name"
                  outlined
                  dense
                ></v-text-field>
              </div>
              <div class="d-flex">
                <v-text-field label="Email" outlined dense></v-text-field>
                <v-text-field
                  class="ml-1"
                  label="Phone"
                  outlined
                  dense
                ></v-text-field>
              </div>
              <div class="d-flex">
                <v-text-field label="Nationality" outlined dense></v-text-field>
                <v-text-field
                  class="ml-1"
                  label="Exacted Salary"
                  outlined
                  dense
                ></v-text-field>
              </div>
              <div class="d-flex flex-column">
                <v-file-input
                  outlined
                  prepend-inner-icon="mdi-paperclip"
                  prepend-icon=""
                  placeholder="Upload your resume"
                  dense
                ></v-file-input>
                <v-file-input
                  outlined
                  prepend-inner-icon="mdi-paperclip"
                  prepend-icon=""
                  placeholder="Upload your photo"
                  class="ml-1"
                  dense
                ></v-file-input>
              </div>
              <v-textarea
                outlined
                name="input-7-4"
                label="Tell us more about yourself"
              ></v-textarea>

              <v-btn
                large
                small
                x-large
                color="blue"
                elevation="0"
              @click="handleSubmitForm()"
                class="ma-0 pa-0 px-15 py-2 mb-2 mt-0"
                ><span class="text-white">Apply Now</span></v-btn
              >
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import TopFilter from '@/components/TopFilter.vue'
import JobsCard from '@/components/JobsCard.vue'

export default {
  components: { TopFilter, JobsCard },
  props: {},
  methods: {
    handleSubmitForm() {
      console.log('form submitted');
      this.$router.push('./thank-you')
    },
  }
}
</script>

<style lang="scss"></style>
